### PR TITLE
use from quick note & requirement

### PR DESCRIPTION
**Pull request by rotty3000**
FYI @eduardolundgren @natecavanaugh here's the working impl. Next step, autogenerate the Req&Cap based on bower.json & config.js

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Nice @rotty3000, we will give a try and let you know. Thank you.

**Comment by rotty3000** [comment]
Tests are coming btw.

**Comment by rotty3000** [comment]
several updates & tests.

This module should now work in standalone env without full Liferay portal around it.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/875. [See changes here.](https://github.com/ipeychev/liferay-portal/compare/aa21a7c~1...aa21a7c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/876. [See changes here.](https://github.com/ipeychev/liferay-portal/compare/66cedf5~1...66cedf5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/877. [See changes here.](https://github.com/ipeychev/liferay-portal/compare/3099751~2...3099751) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
