### PR TITLE
LPS-56239 ant build-ckeditor-plugins-bbcode.

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Hey @zxdgoal,

We cannot automatically convert the new lines to BR. The value inside [code] should be not touchable.
In this situation a BBCode is being parsed and we don't know if the \n has been converted from <br> or \r?\n.
This is bad, but it will be worst to automatically convert all new lines in [code] to BR. What will happen if I copy come real programming code? I wouldn't expect all new lines to be converted to BR.

I don't see how can we fix this issue without breaking something else, but this fix I don't think we should accept.

Thanks,

**Comment by zxdgoal** [comment]
Thanks for your explanation, @ipeychev 

I still have some questions.

>What will happen if I copy come real programming code? I wouldn't expect all new lines to be converted to BR

Could you give me a simple case where this fix breaks?

Those \n and BR should be hidden to the user, and they should not be able to any difference between contents before parsed and after parsed.

Another thing in my mind is that we use enterMode as BR for bbcode plugin, shouldn't we expect this config for code style?
 

Just a reminder, what Byran did fix here: https://github.com/liferay/liferay-ckeditor/compare/8ac2157801c92b11e23586b1a1ec0cf53475bf89~1...794f1786666ff12b8da14b354e7d7e85e082aa52 might relate to this issue.

Many thanks
John.

**Comment by ipeychev** [comment]
Hey @zxdgoal,

Thanks for your comments!

The problem is that we touch something that we shouldn't. With the proposed patch we don't parse anything in [code], *except* new lines. The meaning of [code] is to leave the content as it written by the user. And we change this behaviour in order to solve another issue; this is what makes me nervous.

Check the attached gif. From user's point of view, he created just one [code] block. But when he switches to HTML mode, he cannot remove the [code] block just by pressing the button. He should press multiple times the button and I'm sure this will be reported as a bug too.

Thanks,
bug

**Comment by zxdgoal** [comment]
Hey @ipeychev 

What you believe is a bug is indeed the customer's expected behaviour. They want to be able remove code style for one line at any time.

I see your point. In the source mode, the data is without br, but in the HTML, it is.

So this contradicts your design: 
>The meaning of [code] is to leave the content as it written by the user. 

But we can look at this issue from the perspective of an end user:

He input data with code style under HTML mode and those data is with BR because of https://github.com/liferay/liferay-ckeditor/compare/8ac2157801c92b11e23586b1a1ec0cf53475bf89~1...794f1786666ff12b8da14b354e7d7e85e082aa52.

Now he clicks on the source button twice. What he saw is different from what he input as the BR is missing.

The key point here is when changing from HTML mode to source mode, we do not follow 
>The meaning of [code] is to leave the content as it written by the user as 

```
		_handleBreak: function(element, listTagsIn, listTagsOut) {
			var instance = this;

			if (instance._inPRE) {
				listTagsIn.push(NEW_LINE);
			}
			else if (instance._allowNewLine(element)) {
				listTagsIn.push(NEW_LINE);
			}
		}
```
replace the BR with \n. It does not keep what in PRE intact.

**Comment by ipeychev** [comment]
Hey @zxdgoal,

If this customer expects the the [code] to be removed line by line, then can't you guys create a fix pack especially for him and provide it?

This change is too big to generalize and put to Portal just like this. It does not simply fixes the issue - it changes the way the [code] block is being removed. If we want to change the default behaviuor for everybody, then our UX team should be involved, which will take time. So, if you are in a hurry, create a fix pack, make the customer happy and we can discuss this change with the UX team and take a decision to introduce it for everyone or not.

About not touching [code] blocks, PRE in HTML has nothing to do here. I was talking about Source mode and [code] block. What is important is what is in the database - tomorrow we can remove this editor and replace it with something else. The message in the database should be a valid BBCode. In the View mode of this editor, when user presses Enter, this is being represented as BR. However, in BBCode a new line is being represented with \n, that's why the code you quoted above for handling the lines exists.

One more time - the proposed fix changes the way in which [code] block is being removed - instead to be removed in one pass, now each line is being removed. That is the issue. And it goes in contrary with the rule that we don't make UX changes just like this. We make them carefully.

Hope that helps.

Thanks,

**Comment by zxdgoal** [comment]
Thanks for your detailed explanation again.

Since this fix could have side effects, I will talk with Hugo to deliver a SDH to this customer.

**Comment by ipeychev** [comment]
Okay, thanks!

**Pull request closed without merging**
