### PR TITLE
LPS-53472 In fullscreen, aceEditor height is 100%

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc/ @jbalsas

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/23. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
