### PR TITLE
LPS-56411

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by ipeychev** [comment]
Hey Byran,

Sorry, but till Monday I will be on vacation. If this PR is urgent, please send it to someone else.

Thanks,

**Comment by blzaugg** [comment]
The customer is anticipating a delay.

I wouldn't be able to get to this until the end of the week and I'd need to send it to you anyway.

If it came down to urgency, who would be a good alternative?

**Comment by ipeychev** [comment]
On Jun 17, 2015 11:43 PM, "Byrån Zaugg" <notifications@github.com> wrote:
>
> The customer is anticipating a delay.
>
> I wouldn't be able to get to this until the end of the week and I'd need
to send it to you anyway.
>
> If it came down to urgency, who would be a good alternative?

Maybe Chema, Nate or Eduardo L.?

**Comment by hhuijser** [comment]
Sent to Nate for review: https://github.com/natecavanaugh/liferay-portal/pull/3301
Please close this pull

**Pull request closed without merging**
