### PR TITLE
LPS-54972 Smileys are converted to images inside code block in CKEditor.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey @ipeychev 

This pr extends from https://github.com/ipeychev/liferay-portal/pull/561.

I only include the code changed by `ant build-ckeditor-plugins-bbcode` related to my fixes.

I omitted some changes which will be included  last two commits here: https://github.com/ipeychev/liferay-portal/pull/564 to avoid conflict.

 Related talk: 
https://in.liferay.com/web/support/forums/-/message_boards/message/14902342

Thanks
John.

### CODE REVIEW

**Comment by zxdgoal** [comment]
Code for calculating time consumed:

```
			console.time("parsingTime");

			if (instance._noParse == false) {
				var length = emoticonSymbols.length;

				for (var i = 0; i < length; i++) {
					var image = tplImage.output(
						{
							imageSrc: emoticonPath + emoticonImages[i]
						}
					);

					var escapedSymbol = emoticonSymbols[i].replace(REGEX_ESCAPE_REGEX, '\\$&');

					value = value.replace(new RegExp(escapedSymbol, 'g'), image);
				}
			}

			console.timeEnd("parsingTime")
```

Result
parsingTime: 0.207ms
parsingTime: 0.138ms
parsingTime: 0.245ms
parsingTime: 0.106ms
parsingTime: 0.182ms
parsingTime: 0.280ms
parsingTime: 0.263ms
parsingTime: 0.183ms
parsingTime: 0.145ms
parsingTime: 0.168ms
parsingTime: 0.128ms
parsingTime: 0.159ms
parsingTime: 0.226ms
parsingTime: 0.264ms

**Comment by zxdgoal** [comment]
Code for calculating time consumed:

```
			console.time("parsingTime");

			if (instance._noParse == false) {
				var length = emoticonSymbols.length;

				for (var i = 0; i < length; i++) {
					var image = tplImage.output(
						{
							imageSrc: emoticonPath + emoticonImages[i]
						}
					);

					var escapedSymbol = emoticonSymbols[i].replace(REGEX_ESCAPE_REGEX, '\\$&');

					value = value.replace(new RegExp(escapedSymbol, 'g'), image);
				}
			}

			console.timeEnd("parsingTime")
```

Result
parsingTime: 0.207ms
parsingTime: 0.138ms
parsingTime: 0.245ms
parsingTime: 0.106ms
parsingTime: 0.182ms
parsingTime: 0.280ms
parsingTime: 0.263ms
parsingTime: 0.183ms
parsingTime: 0.145ms
parsingTime: 0.168ms
parsingTime: 0.128ms
parsingTime: 0.159ms
parsingTime: 0.226ms
parsingTime: 0.264ms

**Comment by zxdgoal** [comment]
Hey @ipeychev 

If you are more interested in how much time consumed for whole message, I just did another investigation.

The time varies from how large and what kindle of message used for testing.

I just use a news from http://fiction.eserver.org/novels/alice_in_wonderland.html, hope it is large enough for testing.

Time consumed WITHOUT this fix: 
```
			else {
				console.time('parsingTime');
				
				data = instance._bbcodeConverter.convert(data);

				var length = emoticonSymbols.length;

				for (var i = 0; i < length; i++) {
					var image = TEMPLATE_IMAGE.replace('{image}', emoticonPath + emoticonImages[i]);

					var escapedSymbol = emoticonSymbols[i].replace(REGEX_ESCAPE_REGEX, '\\$&');

					data = data.replace(new RegExp(escapedSymbol, 'g'), image);
				}

				console.timeEnd('parsingTime');
			}
```
Result: 10 times
bbcode_data_processor.js?t=F0EM:149 parsingTime: 19.318ms
bbcode_data_processor.js?t=F0EM:149 parsingTime: 24.846ms
bbcode_data_processor.js?t=F0EM:149 parsingTime: 13.944ms
bbcode_data_processor.js?t=F0EM:149 parsingTime: 38.143ms
bbcode_data_processor.js?t=F0EM:149 parsingTime: 26.753ms
bbcode_data_processor.js?t=F0EM:149 parsingTime: 13.960ms
bbcode_data_processor.js?t=F0EM:149 parsingTime: 17.335ms
bbcode_data_processor.js?t=F0EM:149 parsingTime: 23.468ms
bbcode_data_processor.js?t=F0EM:149 parsingTime: 44.416ms
bbcode_data_processor.js?t=F0EM:149 parsingTime: 13.739ms

Average: 23.58 ms

Time consumed WITH this fix 

```
			else {
				console.time('parsingTime');
				data = instance._bbcodeConverter.convert(data);
				console.timeEnd('parsingTime');
			}
```

Result: 10 times
bbcode_data_processor.js?t=F3K5:154 parsingTime: 162.761ms
bbcode_data_processor.js?t=F3K5:154 parsingTime: 149.572ms
bbcode_data_processor.js?t=F3K5:154 parsingTime: 111.425ms
bbcode_data_processor.js?t=F3K5:154 parsingTime: 115.127ms
bbcode_data_processor.js?t=F3K5:154 parsingTime: 171.371ms
bbcode_data_processor.js?t=F3K5:154 parsingTime: 115.266ms
bbcode_data_processor.js?t=F3K5:154 parsingTime: 110.803ms
bbcode_data_processor.js?t=F3K5:154 parsingTime: 107.673ms
bbcode_data_processor.js?t=F3K5:154 parsingTime: 108.650ms
bbcode_data_processor.js?t=F3K5:154 parsingTime: 109.795ms

Average time : 126.42 ms

**Comment by ipeychev** [comment]
Thanks, John.
This is 500% delay :(
The message you used is huge and it does not represent a typical message board post, but with it we went over the 100ms limit:
"0.1 second is about the limit for having the user feel that the system is reacting instantaneously, meaning that no special feedback is necessary except to display the result."
Google for more info about it.

Since this is for the customer, I will get this PR, but for Liferay 7 we must get rid of this approach...

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3193. [See changes here.](https://github.com/ipeychev/liferay-portal/compare/d53ab68~3...d53ab68) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
