### PR TITLE
LPS-57506 Add missing triggerCssClass attribute to lexicon view

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc/ @sergiogonzalez

**Comment by juliocamarero** [comment]
:+1:

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ipeychev** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29075. [See changes here.](https://github.com/ipeychev/liferay-portal/compare/fe894db~1...fe894db) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
