### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by rotty3000**
prototype of the backend (/o/paths.js), minus generation of compatible bundles, check the bnd file of frontend-js-web to see the basic way to declare the resource 'alias', doesn't yet describe the 'dependencies'. /cc @eduardolundgren

### CODE REVIEW

**Comment by rotty3000** [comment]
I should mention that providing a new *bundle* also requires a `Web-ContextPath` header.

I'm thinking about something like this for *converting* a project with a `bower.json` to an OSGi compatible bundle with runtime resolved dependencies.

We would generate basically the following (approximate) OSGi headers:
*(note this is modelled after an existing RFP submitted to the OSGi alliance)*
```
module-name: liferay
path-to-files-in-module: ...
Provide-Capability:\
    osgi.webresource;osgi.webresource=${module-name};\
    path=${path-to-files-in-module};\
    version:Version=${Bundle-Version}
Require-Capability:\
    osgi.webresource;\
    filter:='(&(osgi.webresource=jquery)(version>=2.1.1)(!(version>3)))';
Web-ContextPath: /osgi.webresource.${module-name}-${Bundle-Version}
```

I'm considering 3 possible options for a developer story (in fact we could do all 3):

**Option 1.** auto recognition of archives (things that can be processed by java zip support) containing `bower.json` and transparently doing the work during the deploy. This might look like a java protocol handler:

* `g> install bower:file:///some/bower/module.zip`
* `g> install bower:http://example.com/package.zip`

Using an java protocol handler through osgi we can transparently convert from a regular zip to a compliant OSGi bundle on the fly.

**Option 2.** provide bower commands in the gogo shell. With this we could make a very familiar environment for developers to install/manage things from bower (and/or npm). Obviously the functionality would be limited but I think we could easily capture the most common uses quite easily:

* `g> bower:install <endpoint>`
* `g> bower:list`
* `g> bower:lookup <name>`
* etc.

**Option 3.** build a plugin for bnd which would allow it to convert a bower project to an OSGi bundle with the proper headers so that you could deploy it directly into the OSGi runtime without any changes.

/cc @eduardolundgren @natecavanaugh

**Comment by rotty3000** [comment]
One other thing to consider which I think is even a more fundamentally missing feature is the ability to register a new js library into `javascript.barebone.files` and `javascript.everything.files`. I have a rough prototype but there are complications related to the fact that all the files listed there assume they are in the same context and at same root path. In fact, I wanted to add the path to `/o/paths.js` dynamically (replacing @ipeychev's static `paths.js`) but that proved complicated due to those assumptions.

Maybe we can come up with an alternative though...

**Comment by rotty3000** [comment]
However, thinking about this further... I think it might be wrong to place the `/o/paths.js` in the javascript bundles due to the fact that those are very heavily cached and merged in the case of fast load.

**Comment by ipeychev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
Hey @rotty3000, let's go with Option 1, automatic generation on deploy.

About barebone files, let's address this feature in a different issue later.

Thank you,

**Pull request closed without merging**
